# Generated by Django 5.2.6 on 2025-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_is_active_customer_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('kaspi', 'Kaspi.kz')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
